---
- name: Converge
  hosts: all
  #become: true

  vars:
    munin_node_allowed_cidrs: ['10.0.0.0/8', '2001:db8::/32']
    munin_node_denied_cidrs: ['10.42.0.0/16', '2001:db8:42::/48']
    munin_node_plugins:
      - name: uptime
      - name: if_eth1
        plugin: if_

    munin_node_config: {
      "ps_test": {
        "env.regex": "bash",
        "env.name": "bash"
      }
    }

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install test dependencies (Debian).
      package: name=netcat state=present
      when: ansible_os_family == 'Debian'

    - name: Install test dependencies (RedHat).
      package: name=nc state=present
      when: ansible_os_family == 'RedHat'

  roles:
    - role: geerlingguy.munin-node
